USE [master]
GO

/****** Object:  Database [FFToiletBowl]    Script Date: 09/27/2017 13:17:36 ******/
CREATE DATABASE [FFToiletBowl] ON  PRIMARY 
( NAME = N'FFToiletBowl', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLSERVER2008\MSSQL\DATA\FFToiletBowl.mdf' , SIZE = 19456KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FFToiletBowl_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLSERVER2008\MSSQL\DATA\FFToiletBowl_log.ldf' , SIZE = 1341696KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [FFToiletBowl] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FFToiletBowl].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FFToiletBowl] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FFToiletBowl] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FFToiletBowl] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FFToiletBowl] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FFToiletBowl] SET ARITHABORT OFF 
GO

ALTER DATABASE [FFToiletBowl] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FFToiletBowl] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [FFToiletBowl] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FFToiletBowl] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FFToiletBowl] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FFToiletBowl] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FFToiletBowl] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FFToiletBowl] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FFToiletBowl] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FFToiletBowl] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FFToiletBowl] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FFToiletBowl] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FFToiletBowl] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FFToiletBowl] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FFToiletBowl] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FFToiletBowl] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FFToiletBowl] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FFToiletBowl] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FFToiletBowl] SET  READ_WRITE 
GO

ALTER DATABASE [FFToiletBowl] SET RECOVERY FULL 
GO

ALTER DATABASE [FFToiletBowl] SET  MULTI_USER 
GO

ALTER DATABASE [FFToiletBowl] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FFToiletBowl] SET DB_CHAINING OFF 
GO

